.gitignore, README.md, package-lock.json, package.json, pom.xml, src/main/java/io/percy/selenium/Environment.java, src/main/java/io/percy/selenium/Percy.java
With this implementation, the client and environment info looks like:
```
"clientInfo":"percy-java-selenium/0.0.1"
"environmentInfo":"selenium-java/MAC/chrome/70.0.3538.77"
```
An example of this library in action can be seen in https://github.com/percy/example-percy-java-selenium/pull/3
=> Initial implementation of percy-java-selenium

package-lock.json, package.json
Dependabot doesn't do npm updates for a project that is marked Java.
=> Bump @percy/agent to 0.1.14

src/main/java/io/percy/selenium/Percy.java
=> Pass enableJavaScript flag to the method

README.md
This PR updates the README to contain setup instructions & docs.
=> 📝  Update README with instructions

.github/workflows/test.yml, README.md, package.json, pom.xml, src/main/java/io/percy/selenium/Percy.java, src/test/java/io/percy/selenium/SdkTest.java, yarn.lock
This PR adds the new `scope` snapshot option, which allows users to capture a screenshot of specific parts of a page.
=> ✨ Add scope snapshot option

README.md, package.json, src/main/java/io/percy/selenium/Percy.java, yarn.lock
Fixes https://github.com/percy/percy-selenium-java/issues/172
=> 🐛 PercyDOM.serialize returns fix now #172

src/main/java/io/percy/selenium/Percy.java, src/test/java/io/percy/selenium/SdkTest.java
Implementing Ignore Region for different types including ignore by id, xpath, selenium webelement and custom ignore region for POA.
=> POA Support for ignoreRegion

package.json, pom.xml, src/main/java/io/percy/selenium/Environment.java
=> 🔖  v2.0.0-beta.0

src/main/java/io/percy/selenium/Percy.java, src/test/java/io/percy/selenium/SdkTest.java
=> Remove RemoteWebdriver check

pom.xml, src/main/java/io/percy/selenium/Environment.java
Release percy selenium java sdk `v2.0.0`
=> :bookmark: release v2.0.0 java-selenium-sdk

src/main/java/io/percy/selenium/Percy.java
Passing DeviceName to capabilities.
=> Pass deviceName in capabilities

pom.xml, src/main/java/io/percy/selenium/Environment.java
🐛  Fix: PoA sessions were having broken ui for selenium version less than 4.5
=> :bookmark: release v2.0.1 percy java selenium sdk

README.md, pom.xml, src/main/java/io/percy/selenium/Cache.java, src/main/java/io/percy/selenium/DriverMetadata.java, src/main/java/io/percy/selenium/Percy.java, src/test/java/io/percy/selenium/CacheTest.java
SDK Caching for Percy Screenshot Command.
=> Pplt 2089/java sdk cache

pom.xml, src/main/java/io/percy/selenium/Environment.java
`Releasing percy-selenium-java v2.0.2-beta.0`
=> Releasing percy-selenium-java v2.0.2-beta.0

pom.xml, src/main/java/io/percy/selenium/Environment.java
Percy Selenium Java `v2.0.2-beta.1`
=> :bookmark: release-v2.0.2-beta.1

README.md, pom.xml, src/main/java/io/percy/selenium/Environment.java
=> :bookmark: release-v2.0.2

README.md
- Updating ReadMe for PoA FullPage
=> 📝 Readme update poa fullpage 

pom.xml, src/main/java/io/percy/selenium/Environment.java
=> :bookmark: v2.0.3

package.json, src/main/java/io/percy/selenium/Percy.java, src/test/java/io/percy/selenium/SdkTest.java
- Timeout to 600 sec.
- Sync implementation.
sync cli response -
=> Synchronous CLI implementation

README.md, pom.xml, src/main/java/io/percy/selenium/Environment.java
:bookmark: release-v2.0.4-beta.0 and Readme update
=> :bookmark: release-v2.0.4-beta.0

package.json, pom.xml, src/main/java/io/percy/selenium/Environment.java
=> :bookmark: v2.0.4

src/main/java/io/percy/selenium/Percy.java
Non Automate projects should not run using percy_screenshot, previously check was only for web projects now making it for all projects apart from automate
=> Non automate session should not use screenshot()

pom.xml, src/main/java/io/percy/selenium/Environment.java
=> 🔖 Releasing v2.0.6-beta.0

pom.xml, src/main/java/io/percy/selenium/Environment.java
=> 🔖 Release v2.1.1-beta.0

pom.xml, src/main/java/io/percy/selenium/Environment.java
=> 🔖 Release v2.1.1
